[phases.setup]
cmds = [
  "install-php-extensions gd"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-gd"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"